import type { Metadata } from "next";

import localFont from "next/font/local";
import { cookies } from "next/headers";

import Navbar from "~/components/layout/navbar/navbar";
import Footer from "~/components/layout/footer";
import { CartProvider } from "~/context/cart-context";
import { getCart } from "~/lib/shopify";

import "~/app/globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const resCookies = await cookies();
  const cartId = resCookies.get("cartId")?.value;

  const cart = getCart(cartId!);

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} font-sans antialiased`}>
        <CartProvider cartPromise={cart}>
          <Navbar />
          {children}
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
